exports.PORT = process.env.PORT || 8000;
exports.CKEY = process.env.CKEY;
exports.URLCAD = process.env.URLCAD;
exports.USERKC = process.env.USERKC;
exports.USERPC = process.env.USERPC;
exports.DATABASE_URL = process.env.DATABASE_URL;
exports.EMAIL=process.env.EMAIL;
exports.EP=process.env.EP;
exports.SENDEMAIL=process.env.SENDEMAIL;